Vet clinic database: query and update animals table
aubinleyoung/Vet-clinic-database pull request #2
Opened 2023-03-28 18:51 UTC by aubinleyoung

## Vet clinic database: query and update animals table
### In this project I:

- [ ] Added a column species of type string to my animal's table. 
- [ ] Insert the given data:
- [ ] Update the animals table by setting the species column to unspecified
- [ ] Inside a transaction:
  - Delete all animals born after Jan 1st, 2022.
  - Create a savepoint for the transaction.
  - Update all animals' weight to be their weight multiplied by -1.
  - Rollback to the savepoint
  - Update all animals' weights that are negative to be their weight multiplied by -1.
  - Commit transaction

- [ ] I took the following screenshot:
<img width="659" alt="Screenshot 2023-03-28 174159" src="https://user-images.githubusercontent.com/87595063/228506575-58a84cca-85d7-4596-a3d6-48ada363aa2f.png">
<img width="664" alt="Screenshot 2023-03-28 203004" src="https://user-images.githubusercontent.com/87595063/228506603-1385bef8-b12f-4a40-92c4-0b0739e4588e.png">
<img width="657" alt="Screenshot 2023-03-28 204615" src="https://user-images.githubusercontent.com/87595063/228506621-3e7ad464-f276-4e44-88b7-01ec69db5e2c.png">
<img width="658" alt="Screenshot 2023-03-28 204846" src="https://user-images.githubusercontent.com/87595063/228506628-d2809fc1-7325-4404-94e9-3edde0a8f8ed.png">
<img width="672" alt="Screenshot 2023-03-28 213131" src="https://user-images.githubusercontent.com/87595063/228506637-b06fc18d-1d32-4126-93c9-17258936d942.png">
<img width="663" alt="Screenshot 2023-03-28 213237" src="https://user-images.githubusercontent.com/87595063/228506644-149a432d-0fba-4909-8750-7bd93c56f40f.png">
<img width="675" alt="Screenshot 2023-03-28 213322" src="https://user-images.githubusercontent.com/87595063/228506650-d56beb63-3898-43c8-980b-7af35f22ecae.png">
<img width="677" alt="Screenshot 2023-03-28 213402" src="https://user-images.githubusercontent.com/87595063/228506659-98b5a4e4-d967-4157-b0de-44fa8298e4d2.png">
<img width="667" alt="Screenshot 2023-03-28 213507" src="https://user-images.githubusercontent.com/87595063/228506665-19d41276-8f1d-415d-b431-1eb4c4f0b3fe.png">
<img width="676" alt="Screenshot 2023-03-28 213635" src="https://user-images.githubusercontent.com/87595063/228506668-51a6883b-3de6-4f06-9f02-b6138872d4ee.png">

2023-03-28 19:27 UTC, Owusu-Desmond requested changes
Hi @aubinleyoung , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 19:27 UTC, Owusu-Desmond commented on data.sql
> +(11,'Ditto', '2022-05-14', 4, true, 22,'unspecified');
- [ ] From [the project requirement](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md), the data that suppose to be inserted into the `animals` table has no values for the species column which means the species columns suppose to be null in the `animals` table :blush: but you set the value to `unspecified` :relaxed:

2023-03-28 19:27 UTC, Owusu-Desmond commented on queries.sql
> +COMMIT;
- [ ] Please make sure that anytime you complete a transaction you need to verify that the changes were made and add a screenshot with a label showing the result of each action. :pray:

2023-03-29 10:34 UTC, AnselemOdims approved these changes
### Hi  @aubinleyoung 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 10:43 UTC, merged